version: '3.8'

services:
  shortener-frontend:
    container_name: shortener-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:3000"
    env_file:
      - .env
    restart: always
    networks:
      - npm_network

networks:
  npm_network:
    external: true
    name: npm_network