# docker-compose.yml
version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4100:3000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge